import type { Metadata } from "next";
import "./globals.css";
import Footer from "@/components/Footer";
import { FooterLandingPage } from "@/components/FooterLandingPage";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased">
        {children}
        <Footer />
        <FooterLandingPage />
      </body>
    </html>
  );
}
