import type { Metadata } from "next";
import "./globals.css";
// import Footer from "@/components/Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pl">
      <body className="antialiased">
        <main className="min-h-screen p-3 bg-[#FCFCFC]">{children}</main>
        {/* przez ten footer rozjezdza sie na malym ekranie */}
        {/* <Footer /> */}
      </body>
    </html>
  );
}
